### ISSUE TITLE
Windows support.

### ISSUE THREAD

**Issue by xiam** [xiam/hyperfox#1]
I think Hyperfox would compile fine on a Windows machine but I can't test it since I don't have a license so some help would be appreciated.

Some concerns:

* Hyperfox depends on [mattn's SQLite driver][1] which requires CGO.
* We need instructions for building and testing from scratch on a VirtualBox's virtual machine and not a binary build.
* Instructions for enabling IP forwarding are also needed.

[1]: https://github.com/mattn/go-sqlite3

**Comment by peterhellberg** [comment]
One idea might be to support [BoltDB](https://github.com/boltdb/bolt) (or [goleveldb](https://github.com/syndtr/goleveldb)) as the storage backend? Is thera any other parts of this project that requires CGO?

**Comment by xiam** [comment]
The thing with SQLite is that it creates a practically universally known database file that can be read with the `sqlite` command line tool and also with many visual tools. This way the user is never locked to an specific tool for reading her data. The drawback is that compilation is not that straightforward.

It would be great to get rid of CGO, that way cross compilation would not be a problem and we'll definitely do it when we can offer a good option against the data locking issue.

I've opened a [separate issue][4] to discuss [boltdb][1], [goleveldb][2] and [ql][3] as potential storage backends and included all my concerns.

PS: On the meantime, I plan to offer binaries soon so the user does not have to compile from source.

[1]:https://github.com/boltdb/bolt
[2]:https://github.com/syndtr/goleveldb
[3]: https://github.com/cznic/ql
[4]: https://github.com/xiam/hyperfox/issues/2

**Comment by mdaniel** [comment]
>  I can't test it since I don't have a license so some help would be appreciated.

Just as a friendly FYI, Microsoft makes [VM images](https://www.modern.ie/en-us/virtualization-tools#downloads) available for almost every platform they sell. Compilation can then proceed using either [MinGW](http://mingw-w64.sourceforge.net/download.php)^1, [TDM-GCC](http://tdm-gcc.tdragon.net/about) or [Windows SDK](http://www.microsoft.com/en-us/download/details.aspx?id=3138) [also available as an [ISO](http://go.microsoft.com/fwlink/?LinkID=150216&clcid=0x409)] which last time I checked included `cl.exe` as well as all the Microsoft headers required to compile for the platform.

I am not a lawyer, but the freely available downloads implies to me that Microsoft wants you to compile for its users, in hopes they'll remain on Windows.

1 = Please see this text for the story with MinGW-x64: http://qt-project.org/wiki/MinGW-64-bit and this site which was linked from the MinGW download page looks great: http://win-builds.org/

**Comment by xiam** [comment]
Thanks! That's a good one. @peterhellberg also pointed me out to the modern.ie website on the Gophers channel on Slack, these images are good for 30 days and that's good enough. Sounds like a really strong alternative.

**Comment by xiam** [comment]
Thanks for your help, I used modern.ie and MinGW as suggested and now we have a Windows build :-).
