### ISSUE TITLE
`dsniff` link on  https://hyperfox.org/capturing-https-traffic points to the sample CA certificate

### ISSUE THREAD

**Issue by oko** [xiam/hyperfox#3]
The link to `dsniff` near the bottom of the ["Capturing HTTPS Traffic"](https://hyperfox.org/capturing-https-traffic) page points to the sample CA certificate on the GitHub repo rather than the [`dsniff` website](http://www.monkey.org/~dugsong/dsniff/).

**Comment by xiam** [comment]
Thanks Jacob!
