### ISSUE TITLE
TLS oversized record error

### ISSUE THREAD

**Issue by 9uuso** [xiam/hyperfox#7]
Hi,

I'm trying to setup HTTPs capturing, but I'm receiving multiple errors like this when initializing HTTPs requests:

```
2015/03/08 12:48:15 http: TLS handshake error from 192.168.0.102:52759: tls: oversized record received with length 20037
```

I'm running the latest OS X and have followed the tutorials on https://hyperfox.org/capturing-https-traffic. Hyperfox version is 0.9. HTTP capturing works fine.

Any idea what might be wrong?

**Comment by chenzx** [comment]
I have the same problem:

2015/12/20 16:21:33 http: TLS handshake error from 127.0.0.1:53250: tls: oversized record received with length 20037
2015/12/20 16:21:33 http: TLS handshake error from 127.0.0.1:53251: tls: oversized record received with length 20037
2015/12/20 16:21:41 http: TLS handshake error from 127.0.0.1:53258: tls: oversized record received with length 20037
2

seems https proxy doesn't work for Chome.

**Comment by 9uuso** [comment]
I used Chromium, so that might been it. I recall getting hyperfox to work eventually, but I cant remember whether it was on Chromium or Firefox.

**Comment by ring04h** [comment]
因为heartbleed漏洞, 所以golang限制了密文的长度，自己自定义生成一组证书指定进去
./hyperfox.bin -c="./ssl/rootCA.crt" -k="./ssl/rootCA.key"

**Comment by ring04h** [comment]
https://github.com/pipeviz/pipeviz/issues/198
Upgrade your golang language, don't use https://hyperfox.org/files/*.bin
it's too old, Two years ago

**Comment by arashmolavi** [comment]
I am also facing this issue! Is there now a solution for this, as the thread has been closed?

I am using: 

- OS X El Capitan
- Hyperfox v1.9.7
- Firefox 49.0.2
- go1.7.3

HTTP works fine, but HTTPS keeps throwing the same error as reported above:

`2016/11/15 13:41:37 http: TLS handshake error from 127.0.0.1:55926: tls: oversized record received with length 20037
`

**Comment by a-a-m** [comment]
Faced with the same issue:

`tls: oversized record received with length 20037`

Still looking for solution.

**Comment by niktrix** [comment]
Facing same issue 

  tls: oversized record received with length 20037
